# Generated by Django 4.0.2 on 2022-03-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklisted_survey_code', models.CharField(blank=True, max_length=20, null=True)),
                ('replaced_survey_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('difficulty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('scent', models.IntegerField()),
                ('size', models.IntegerField()),
                ('sunlight', models.IntegerField()),
                ('water_cycle', models.IntegerField()),
                ('survey_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
